/**
 * Export Service
 * Handles exporting workspaces to PDF and Markdown formats
 */

import jsPDF from "jspdf";
import type { WorkspaceWithModules } from "@/lib/database/workspace-service";
import type { Block } from "@/types";
import { BlockType } from "@/types";

/**
 * Export workspace to Markdown
 */
export function exportToMarkdown(workspace: WorkspaceWithModules): string {
  let markdown = `# ${workspace.name}\n\n`;
  markdown += `**Company:** ${workspace.companyName}\n`;

  if (workspace.companyUrl) {
    markdown += `**Website:** ${workspace.companyUrl}\n`;
  }

  markdown += `\n---\n\n`;

  // Add strategy summary if available
  if (workspace.generatedStrategy) {
    markdown += `## Strategy Overview\n\n`;
    markdown += `${workspace.generatedStrategy.summary}\n\n`;
    markdown += `---\n\n`;
  }

  // Export each module
  workspace.modules.forEach((module) => {
    markdown += `## ${module.title}\n\n`;
    markdown += blocksToMarkdown(module.blocks);
    markdown += `\n---\n\n`;
  });

  // Add footer
  markdown += `\n*Generated by Campus GTM on ${new Date().toLocaleDateString()}*\n`;

  return markdown;
}

/**
 * Export workspace to PDF
 */
export function exportToPDF(workspace: WorkspaceWithModules): void {
  const pdf = new jsPDF();
  let yPosition = 20;
  const pageHeight = pdf.internal.pageSize.height;
  const pageWidth = pdf.internal.pageSize.width;
  const margin = 20;
  const maxWidth = pageWidth - 2 * margin;

  // Helper to add new page if needed
  const checkPageBreak = (height: number) => {
    if (yPosition + height > pageHeight - 20) {
      pdf.addPage();
      yPosition = 20;
    }
  };

  // Title
  pdf.setFontSize(24);
  pdf.setFont("helvetica", "bold");
  pdf.text(workspace.name, margin, yPosition);
  yPosition += 10;

  // Company info
  pdf.setFontSize(12);
  pdf.setFont("helvetica", "normal");
  pdf.text(`Company: ${workspace.companyName}`, margin, yPosition);
  yPosition += 7;

  if (workspace.companyUrl) {
    pdf.text(`Website: ${workspace.companyUrl}`, margin, yPosition);
    yPosition += 7;
  }

  yPosition += 10;

  // Strategy summary
  if (workspace.generatedStrategy) {
    checkPageBreak(30);
    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text("Strategy Overview", margin, yPosition);
    yPosition += 7;

    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");
    const summaryLines = pdf.splitTextToSize(
      workspace.generatedStrategy.summary,
      maxWidth
    );
    summaryLines.forEach((line: string) => {
      checkPageBreak(7);
      pdf.text(line, margin, yPosition);
      yPosition += 5;
    });
    yPosition += 10;
  }

  // Export each module
  workspace.modules.forEach((module) => {
    checkPageBreak(20);

    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text(module.title, margin, yPosition);
    yPosition += 10;

    module.blocks.forEach((block) => {
      const blockHeight = estimateBlockHeight(pdf, block, maxWidth);
      checkPageBreak(blockHeight);
      yPosition = addBlockToPDF(pdf, block, margin, yPosition, maxWidth);
    });

    yPosition += 10;
  });

  // Footer
  checkPageBreak(10);
  pdf.setFontSize(8);
  pdf.setFont("helvetica", "italic");
  pdf.text(
    `Generated by Campus GTM on ${new Date().toLocaleDateString()}`,
    margin,
    yPosition
  );

  // Download the PDF
  pdf.save(`${workspace.name.replace(/\s+/g, "_")}_GTM_Strategy.pdf`);
}

/**
 * Download workspace as Markdown file
 */
export function downloadMarkdown(workspace: WorkspaceWithModules): void {
  const markdown = exportToMarkdown(workspace);
  const blob = new Blob([markdown], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${workspace.name.replace(/\s+/g, "_")}_GTM_Strategy.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Convert blocks to Markdown
 */
function blocksToMarkdown(blocks: Block[]): string {
  let markdown = "";

  blocks.forEach((block) => {
    switch (block.type) {
      case BlockType.HEADING_1:
        markdown += `# ${block.content}\n\n`;
        break;
      case BlockType.HEADING_2:
        markdown += `## ${block.content}\n\n`;
        break;
      case BlockType.HEADING_3:
        markdown += `### ${block.content}\n\n`;
        break;
      case BlockType.BULLET_LIST:
        markdown += `- ${block.content}\n`;
        break;
      case BlockType.CHECKLIST:
        const checked = block.metadata?.checked ? "x" : " ";
        markdown += `- [${checked}] ${block.content}\n`;
        break;
      case BlockType.QUOTE:
        markdown += `> ${block.content}\n\n`;
        break;
      case BlockType.AI_BLOCK:
        markdown += `**AI Generated:**\n${block.content}\n\n`;
        break;
      case BlockType.TEXT:
      default:
        markdown += `${block.content}\n\n`;
        break;
    }
  });

  return markdown;
}

/**
 * Add block to PDF
 */
function addBlockToPDF(
  pdf: jsPDF,
  block: Block,
  x: number,
  y: number,
  maxWidth: number
): number {
  let currentY = y;

  switch (block.type) {
    case BlockType.HEADING_1:
      pdf.setFontSize(16);
      pdf.setFont("helvetica", "bold");
      pdf.text(block.content, x, currentY);
      currentY += 10;
      break;

    case BlockType.HEADING_2:
      pdf.setFontSize(14);
      pdf.setFont("helvetica", "bold");
      pdf.text(block.content, x, currentY);
      currentY += 8;
      break;

    case BlockType.HEADING_3:
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "bold");
      pdf.text(block.content, x, currentY);
      currentY += 7;
      break;

    case BlockType.BULLET_LIST:
      pdf.setFontSize(10);
      pdf.setFont("helvetica", "normal");
      pdf.text("•", x, currentY);
      const bulletLines = pdf.splitTextToSize(block.content, maxWidth - 10);
      bulletLines.forEach((line: string, index: number) => {
        pdf.text(line, x + 5, currentY + index * 5);
      });
      currentY += bulletLines.length * 5 + 2;
      break;

    case BlockType.CHECKLIST:
      pdf.setFontSize(10);
      pdf.setFont("helvetica", "normal");
      const checkbox = block.metadata?.checked ? "☑" : "☐";
      pdf.text(checkbox, x, currentY);
      const checklistLines = pdf.splitTextToSize(block.content, maxWidth - 10);
      checklistLines.forEach((line: string, index: number) => {
        pdf.text(line, x + 5, currentY + index * 5);
      });
      currentY += checklistLines.length * 5 + 2;
      break;

    case BlockType.QUOTE:
      pdf.setFontSize(10);
      pdf.setFont("helvetica", "italic");
      const quoteLines = pdf.splitTextToSize(block.content, maxWidth - 5);
      quoteLines.forEach((line: string, index: number) => {
        pdf.text(`"${line}"`, x + 5, currentY + index * 5);
      });
      currentY += quoteLines.length * 5 + 5;
      break;

    case BlockType.TEXT:
    default:
      pdf.setFontSize(10);
      pdf.setFont("helvetica", "normal");
      const textLines = pdf.splitTextToSize(block.content, maxWidth);
      textLines.forEach((line: string, index: number) => {
        pdf.text(line, x, currentY + index * 5);
      });
      currentY += textLines.length * 5 + 3;
      break;
  }

  return currentY;
}

/**
 * Estimate block height for pagination
 */
function estimateBlockHeight(
  pdf: jsPDF,
  block: Block,
  maxWidth: number
): number {
  switch (block.type) {
    case BlockType.HEADING_1:
      return 10;
    case BlockType.HEADING_2:
      return 8;
    case BlockType.HEADING_3:
      return 7;
    case BlockType.BULLET_LIST:
    case BlockType.CHECKLIST: {
      const lines = pdf.splitTextToSize(block.content, maxWidth - 10);
      return lines.length * 5 + 2;
    }
    case BlockType.QUOTE: {
      const lines = pdf.splitTextToSize(block.content, maxWidth - 5);
      return lines.length * 5 + 5;
    }
    case BlockType.TEXT:
    default: {
      const lines = pdf.splitTextToSize(block.content, maxWidth);
      return lines.length * 5 + 3;
    }
  }
}
